name: undangon

services:
  server:
    build:
      context: .
      target: dev
    environment:
      - FEATHERS_SECRET=value
    ports:
      - 9876:3030

  mysql:
    image: mysql
    # restart: always
    user: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=undangon_server
      - POSTGRES_PASSWORD=password
    # expose:
    #   - 5432
    ports:
      - 54321:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
