[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm-9_x']

# [phases.build]
# cmds = ['pnpm build']

[phases.install]
cmd = 'pnpm i --frozen-lockfile'

[phases.migrate]
cmd = 'pnpm migrate'

[start]
# cmd = 'pnpm start'
cmd = 'node start.cjs'